//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcumaticaValidations
{
    using System;
    using System.Collections.Generic;
    
    public partial class OAuth
    {
        public long Id { get; set; }
        public Nullable<System.Guid> ProcGUID { get; set; }
        public Nullable<short> EventType { get; set; }
        public string Host { get; set; }
        public string Path { get; set; }
        public string QueryString { get; set; }
        public string Headers { get; set; }
        public string Cookies { get; set; }
        public string Body { get; set; }
        public string StatusCode { get; set; }
        public Nullable<System.DateTime> DT { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public string ClientId { get; set; }
        public string RedirectUri { get; set; }
        public string Scope { get; set; }
        public string TokenType { get; set; }
        public string AccessToken { get; set; }
        public string RefreshToken { get; set; }
        public string ExpiresIn { get; set; }
        public string ResponseType { get; set; }
        public string GrantType { get; set; }
        public string ClientSecret { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}
