//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcumaticaValidations
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestAPI
    {
        public long Id { get; set; }
        public string TypeOfWebService { get; set; }
        public Nullable<short> IsAcumaticaRequest { get; set; }
        public Nullable<short> TypeOfRequest { get; set; }
        public string SiteURL { get; set; }
        public string SessionID { get; set; }
        public string AuthenticationType { get; set; }
        public string Filters { get; set; }
        public string Select { get; set; }
        public string Expands { get; set; }
        public string EndpointName { get; set; }
        public string EndpointVersion { get; set; }
        public string EndpointEntity { get; set; }
        public string ErrorCode { get; set; }
        public string ErrorMessage { get; set; }
        public string AccessScope { get; set; }
        public string NumberOfDetails { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public string DocumentID { get; set; }
    }
}
