//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcumaticaValidations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebRequestEntities : DbContext
    {
        public WebRequestEntities(string name)
            : base(name)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Other> Other { get; set; }
        public virtual DbSet<OData> ODatas { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<OAuth> OAuths { get; set; }
        public virtual DbSet<RestAPI> RestAPIs { get; set; }
    }
}
